// Shared parser options exposed by the command schema.
export const CLI_OPTIONS = {
  "non-interactive": { type: "boolean" },
  offset: { type: "string" },
  fields: { type: "string" },
  expect: { type: "string" },
  "idempotency-key": { type: "string" },
  repo: { type: "string", short: "C" },
  roll: { type: "string", short: "r" },
  help: { type: "boolean", short: "h" },
  json: { type: "boolean" },
  yes: { type: "boolean", short: "y" },
  title: { type: "string" },
  set: { type: "string" },
  editor: { type: "boolean" },
  code: { type: "boolean" },
  save: { type: "string" },
  all: { type: "boolean" },
  mine: { type: "boolean" },
  theirs: { type: "boolean" },
  tag: { type: "string", short: "t", multiple: true },
  file: { type: "string", short: "f", multiple: true },
  at: { type: "string" },
  amount: { type: "string" },
  text: { type: "string" },
  limit: { type: "string", short: "n" },
  github: { type: "boolean" },
  owner: { type: "string" },
  template: { type: "string" },
  dir: { type: "string" },
  "delete-files": { type: "boolean" },
  "read-only": { type: "boolean" },
  field: { type: "string", multiple: true },
  format: { type: "string" },
  output: { type: "string", short: "o" },
  port: { type: "string" },
  "no-browser": { type: "boolean" },
  "dry-run": { type: "boolean" },
  interactive: { type: "boolean", short: "i" },
  plain: { type: "boolean" },
  version: { type: "boolean", short: "v" },
  mode: { type: "string" },
  timezone: { type: "string" },
  "max-bytes": { type: "string" },
  "max-entries": { type: "string" },
  "archive-after": { type: "string" },
  compress: { type: "boolean" },
  "include-archive": { type: "boolean" },
  auto: { type: "boolean" },
  rebuild: { type: "boolean" },
  to: { type: "string" },
} as const;
