// Shared parser options exposed by the command schema.
export const CLI_OPTIONS = {
  "non-interactive": { type: "boolean" },
  offset: { type: "string" },
  fields: { type: "string" },
  expect: { type: "string" },
  "idempotency-key": { type: "string" },
  repo: { type: "string", short: "C" },
  roll: { type: "string", short: "r" },
  help: { type: "boolean", short: "h" },
  json: { type: "boolean" },
  yes: { type: "boolean", short: "y" },
  title: { type: "string" },
  set: { type: "string" },
  editor: { type: "boolean" },
  code: { type: "boolean" },
  save: { type: "string" },
  all: { type: "boolean" },
  mine: { type: "boolean" },
  theirs: { type: "boolean" },
  since: { type: "string" },
  until: { type: "string" },
  include: { type: "string" },
  only: { type: "string" },
  author: { type: "string" },
  label: { type: "string", multiple: true },
  status: { type: "string" },
  branch: { type: "string" },
  project: { type: "string", short: "p", multiple: true },
  tag: { type: "string", short: "t", multiple: true },
  file: { type: "string", short: "f", multiple: true },
  data: { type: "string", short: "d", multiple: true },
  at: { type: "string" },
  amount: { type: "string" },
  text: { type: "string" },
  limit: { type: "string", short: "n" },
  github: { type: "boolean" },
  owner: { type: "string" },
  template: { type: "string" },
  dir: { type: "string" },
  "delete-files": { type: "boolean" },
  "read-only": { type: "boolean" },
  field: { type: "string", multiple: true },
  model: { type: "string" },
  endpoint: { type: "string" },
  "api-key-env": { type: "string" },
  "allow-remote": { type: "boolean" },
  format: { type: "string" },
  output: { type: "string", short: "o" },
  port: { type: "string" },
  "no-browser": { type: "boolean" },
  event: { type: "string" },
  "dry-run": { type: "boolean" },
  interactive: { type: "boolean", short: "i" },
  plain: { type: "boolean" },
  version: { type: "boolean", short: "v" },
  "remove-settings": { type: "boolean" },
} as const;
